name: Weatherly
description: An instant weather reporter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter #Framework used to develop for Android and IOS
  auto_size_text: ^3.0.0 #Autosizes quips and location on the weather screen
  cupertino_icons: ^0.1.2 #Provides icons for the weather screen
  geolocator: ^3.0.1
  http: ^0.12.0+2
  flutter_spinkit: ^3.1.0   

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900